name: Deploy MyHireShield

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Git ownership fix
            git config --global --add safe.directory /var/www/myhireshield
            
            cd /var/www/myhireshield
            # Purane local changes ko force clear karna
            git fetch origin
            git reset --hard origin/main
            
            # Backend update
            cd server
            npm install
            pm2 restart hireshield-api || pm2 start server.js --name "hireshield-api"
            
            # Frontend Update
            cd ../client
            npm install
            rm -rf dist
            chmod +x node_modules/.bin/vite
            npm run build
            
            # Permissions fix
            sudo chown -R www-data:www-data /var/www/myhireshield/client/dist
            sudo chmod -R 755 /var/www/myhireshield/client/dist
            sudo systemctl reload nginx